version: 2.1

orbs:
  slack: circleci/slack@4.10.1

executors:
  # executors
  # [go_base] :
  # - docker
  # の job で使われている。
  go_base:
    docker:
      - image: golang:latest

jobs:
  go_build: # job名
    executor: progate_base # executor名
    steps:
      - checkout
      - run:
          name: go build
          command: go build -o main
      - store_artifacts:
          path: main
          destination: main
      - persist_to_workspace:
          root: .
          paths:
            - main
workflows:
  send-notification:
    jobs:
      - go_build:
